services:
    mongo:
        image: "mongo:latest"
        hostname: "workspace-mongo"
        expose:
            - "27017"
        volumes:
            - mongo-db:/data/db
            - mongo-config:/data/configdb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    # monitoring:
    #     image: "netdata/netdata:latest"
    #     hostname: "workspace-monitor"
    #     ports:
    #         - "19999:19999"
    #     volumes:
    #         - /sys:/host/sys
    #         - /etc/os-release
    #         - netdataconfig:/etc/netdata
    #         - netdatalib:/var/lib/netdata
    #         - netdatacache:/var/cache/netdata
    #         - /etc/passwd:/host/etc/passwd
    #         - /etc/group:/host/etc/group
    #         - /proc:/host/proc

    linnea:
        image: "registry.workspace.pm/workspace/linnea:latest"
        hostname: "workspace-linnea"
        expose:
            - "80"
        environment:
            - LICENSEES=https://{0}.{$DOMAIN}
            - WORKSPACE_DB_CONNECTIONSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@workspace-mongo:27017
            - WORKSPACE_MASTERPASSWORD=${MASTERPASSWORD}
        depends_on:
            - mongo
        links:
            - "mongo:workspace-mongo"

    iris:
        image: "registry.workspace.pm/workspace/iris:latest"
        hostname: "workspace-iris"
        expose:
            - "80"
        environment:
            - AUTH_DB_CONNECTIONSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@workspace-mongo:27017
            - AUTH_DOMAIN=${AUTH_DOMAIN}
            - AUTH_DOMAIN_PORT=${AUTH_DOMAIN_PORT}
            - AUTH_AUTHDOMAIN=${AUTH_AUTHDOMAIN}
            - ENCRYPTION_KEY=${ENCRYPTIONKEY}
            - SCHEME=${SCHEME}
        depends_on:
            - mongo
        links:
            - "mongo:workspace-mongo"

    serverside:
        image: "registry.workspace.pm/workspace/serverside:latest"
        hostname: "workspace"
        expose:
            - "80"
        environment:
            - WORKSPACE_AUTH_SERVER=https://auth.${AUTH_DOMAIN_PORT}
            - WORKSPACE_DB_CONNECTIONSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@workspace-mongo:27017
            - WORKSPACE_DOMAIN={$DOMAIN}
            - WORKSPACE_ENCRYPTION_KEY=${ENCRYPTIONKEY}
        volumes:
            - tenantdata:/app/wwwroot/tenantdata/
        depends_on:
            - mongo
        links:
            - "mongo:workspace-mongo"
    
    reverseproxy:
        image: "nginx:latest"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/public.crt:/var/lib/wsdata/nginx/public.crt
            - ./nginx/private.key:/var/lib/wsdata/nginx/private.key
        ports:
            - ${PORT_HTTP}:80
            - ${PORT_HTTPS}:443
        links:
            - "linnea:workspace-linnea"
            - "iris:workspace-iris"
            - "serverside:workspace"

volumes:
    mongo-db:
    mongo-config:
    netdataconfig:
    netdatalib:
    netdatacache:
    tenantdata: